package com.bytedance.ai.graph.intent;

public enum MainIntent {

    FUZZY_RECOMMEND,
    CONDITION_FILTER,
    MULTI_TURN_REFINE,
    NEGATIVE_CONSTRAINT,
    SCENE_BUNDLE_RECOMMEND,
    PHOTO_SEARCH,

    PRODUCT_RECOMMEND,
    PRODUCT_SEARCH,
    PRODUCT_COMPARE,
    PRODUCT_DETAIL_QUERY,

    PRICE_QUERY,
    INVENTORY_QUERY,
    ORDER_QUERY,
    LOGISTICS_QUERY,

    ADD_TO_CART,
    REMOVE_FROM_CART,
    UPDATE_CART_ITEM,
    CART_MANAGE,
    CREATE_ORDER,
    CONFIRM_ORDER,
    CANCEL_ORDER,
    ORDER_MANAGE,

    POLICY_QA,
    REVIEW_SUMMARY,

    CLARIFY,
    OTHER,
    SMALL_TALK,
    UNKNOWN
}
