CREATE TABLE IF NOT EXISTS rag_documents (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_type VARCHAR(32) NOT NULL,
    source_uri VARCHAR(1024),
    external_ref VARCHAR(255),
    title VARCHAR(512),
    content CLOB NOT NULL,
    content_sha256 CHAR(64) NOT NULL,
    indexed_generation BIGINT,
    status VARCHAR(16) NOT NULL DEFAULT 'PENDING',
    chunk_count INTEGER NOT NULL DEFAULT 0,
    attempt_count INTEGER NOT NULL DEFAULT 0,
    metadata CLOB NOT NULL DEFAULT '{}',
    last_error CLOB,
    last_attempted_at TIMESTAMP,
    indexed_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS rag_index_jobs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    document_id BIGINT NOT NULL,
    content_sha256 CHAR(64) NOT NULL,
    status VARCHAR(16) NOT NULL DEFAULT 'QUEUED',
    stage VARCHAR(32) NOT NULL DEFAULT 'QUEUED',
    version BIGINT NOT NULL DEFAULT 0,
    last_event VARCHAR(64),
    attempt_count INTEGER NOT NULL DEFAULT 0,
    target_generation BIGINT,
    message_id VARCHAR(128),
    last_error CLOB,
    started_at TIMESTAMP,
    finished_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_rag_index_jobs_document_sha UNIQUE (document_id, content_sha256)
);

CREATE TABLE IF NOT EXISTS rag_index_job_transitions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    document_id BIGINT NOT NULL,
    job_id BIGINT,
    outbox_id BIGINT,
    content_sha256 CHAR(64) NOT NULL,
    from_state VARCHAR(32),
    to_state VARCHAR(32) NOT NULL,
    event VARCHAR(64) NOT NULL,
    trigger_type VARCHAR(32) NOT NULL,
    triggered_by VARCHAR(255),
    success BOOLEAN NOT NULL DEFAULT TRUE,
    failure_reason VARCHAR(64),
    error_message CLOB,
    message_id VARCHAR(128),
    metadata CLOB NOT NULL DEFAULT '{}',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS rag_index_outbox (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    document_id BIGINT NOT NULL,
    content_sha256 CHAR(64) NOT NULL,
    event_type VARCHAR(32) NOT NULL,
    status VARCHAR(16) NOT NULL DEFAULT 'NEW',
    attempt_count INTEGER NOT NULL DEFAULT 0,
    message_id VARCHAR(128),
    last_error CLOB,
    next_attempt_at TIMESTAMP,
    dispatched_at TIMESTAMP,
    consumed_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_rag_index_outbox_document_sha_event UNIQUE (document_id, content_sha256, event_type)
);

CREATE TABLE IF NOT EXISTS rag_index_message_failures (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    message_id VARCHAR(128) NOT NULL,
    topic VARCHAR(255) NOT NULL,
    delivery_attempt INTEGER NOT NULL,
    failure_type VARCHAR(32) NOT NULL,
    error_message CLOB,
    payload_base64 CLOB,
    payload_preview CLOB,
    properties_json CLOB NOT NULL DEFAULT '{}',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS rag_chunks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    document_id BIGINT NOT NULL,
    index_generation BIGINT NOT NULL DEFAULT 1,
    chunk_index INTEGER NOT NULL,
    chunk_text CLOB NOT NULL,
    chunk_hash CHAR(64) NOT NULL,
    char_count INTEGER NOT NULL DEFAULT 0,
    token_count INTEGER,
    vector_id VARCHAR(128),
    metadata CLOB NOT NULL DEFAULT '{}',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_rag_chunks_document_generation_chunk UNIQUE (document_id, index_generation, chunk_index)
);

CREATE TABLE IF NOT EXISTS rag_embedding_cache (
    chunk_hash CHAR(64) NOT NULL,
    embedding_model VARCHAR(255) NOT NULL,
    embedding_dimension INTEGER NOT NULL,
    embedding_json CLOB NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (chunk_hash, embedding_model, embedding_dimension)
);

CREATE TABLE IF NOT EXISTS rag_users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id VARCHAR(128) NOT NULL UNIQUE,
    metadata CLOB NOT NULL DEFAULT '{}',
    first_seen_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_seen_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS rag_conversations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    conversation_id VARCHAR(128) NOT NULL UNIQUE,
    user_id VARCHAR(128) NOT NULL,
    title VARCHAR(200),
    status VARCHAR(16) NOT NULL DEFAULT 'ACTIVE',
    message_count INTEGER NOT NULL DEFAULT 0,
    metadata CLOB NOT NULL DEFAULT '{}',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_message_at TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_rag_conversations_user_cursor
    ON rag_conversations(user_id, last_message_at DESC, id DESC);

CREATE TABLE IF NOT EXISTS rag_conversation_messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    message_id VARCHAR(128) NOT NULL UNIQUE,
    conversation_id BIGINT NOT NULL,
    role VARCHAR(16) NOT NULL,
    content CLOB NOT NULL,
    status VARCHAR(16) NOT NULL DEFAULT 'SUCCEEDED',
    token_count INTEGER,
    correlation_id VARCHAR(128),
    sequence_no INTEGER NOT NULL,
    metadata CLOB NOT NULL DEFAULT '{}',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_rag_messages_conversation_sequence
        UNIQUE (conversation_id, sequence_no)
);

CREATE INDEX IF NOT EXISTS idx_rag_messages_conversation_sequence
    ON rag_conversation_messages(conversation_id, sequence_no);

CREATE TABLE IF NOT EXISTS rag_ask_runs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    run_id VARCHAR(128) NOT NULL UNIQUE,
    correlation_id VARCHAR(128) NOT NULL UNIQUE,
    user_id VARCHAR(128) NOT NULL,
    conversation_id BIGINT NOT NULL,
    user_message_id BIGINT,
    assistant_message_id BIGINT,
    request_id VARCHAR(128),
    question CLOB NOT NULL,
    retrieval_question CLOB,
    top_k INTEGER,
    filters CLOB NOT NULL DEFAULT '{}',
    retrieval_queries CLOB NOT NULL DEFAULT '[]',
    retrieved_contexts CLOB NOT NULL DEFAULT '[]',
    notices CLOB NOT NULL DEFAULT '[]',
    generated_by_model BOOLEAN NOT NULL DEFAULT FALSE,
    degraded BOOLEAN NOT NULL DEFAULT FALSE,
    status VARCHAR(16) NOT NULL DEFAULT 'RUNNING',
    error_code VARCHAR(64),
    error_message CLOB,
    started_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    completed_at TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_rag_ask_runs_user_started
    ON rag_ask_runs(user_id, started_at DESC);

CREATE INDEX IF NOT EXISTS idx_rag_ask_runs_conversation_started
    ON rag_ask_runs(conversation_id, started_at DESC);

CREATE UNIQUE INDEX IF NOT EXISTS uq_rag_ask_runs_request
    ON rag_ask_runs(user_id, conversation_id, request_id);

CREATE TABLE IF NOT EXISTS agent_turn (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    turn_id VARCHAR(64) NOT NULL UNIQUE,
    correlation_id VARCHAR(64) NOT NULL UNIQUE,
    user_id VARCHAR(64) NOT NULL,
    conversation_id VARCHAR(64) NOT NULL,
    request_id VARCHAR(64),
    user_message_id VARCHAR(64),
    assistant_message_id VARCHAR(64),
    status VARCHAR(16) NOT NULL DEFAULT 'RUNNING',
    user_message CLOB NOT NULL,
    intent VARCHAR(32),
    intent_source VARCHAR(16),
    intent_confidence DECIMAL(4, 3),
    slots_json CLOB NOT NULL DEFAULT '{}',
    tools_called CLOB NOT NULL DEFAULT '[]',
    cards_emitted CLOB NOT NULL DEFAULT '[]',
    generated_by_model BOOLEAN,
    answer_text CLOB,
    tokens_in INTEGER,
    tokens_out INTEGER,
    latency_ms INTEGER,
    error_code VARCHAR(64),
    error_message CLOB,
    started_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    completed_at TIMESTAMP
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_agent_turn_idempotency
    ON agent_turn(user_id, conversation_id, request_id);

CREATE INDEX IF NOT EXISTS idx_agent_turn_conv_started
    ON agent_turn(conversation_id, started_at DESC);

CREATE INDEX IF NOT EXISTS idx_agent_turn_user_started
    ON agent_turn(user_id, started_at DESC);

-- catalog (H2 fallback：用 CLOB 模拟 PG 的 jsonb，JdbcCatalog* repository 通过 DB metadata 走非-PG 分支)
CREATE TABLE IF NOT EXISTS catalog_spu (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    external_ref VARCHAR(64) NOT NULL UNIQUE,
    title VARCHAR(255) NOT NULL,
    brand VARCHAR(64),
    category_path VARCHAR(255),
    price_min DECIMAL(10, 2),
    price_max DECIMAL(10, 2),
    stock INTEGER NOT NULL DEFAULT 0,
    description_md CLOB,
    images CLOB NOT NULL DEFAULT '[]',
    video_url VARCHAR(512),
    attributes_json CLOB NOT NULL DEFAULT '{}',
    attributes_status VARCHAR(16) NOT NULL DEFAULT 'PENDING',
    attributes_attempt_count INTEGER NOT NULL DEFAULT 0,
    attributes_last_error CLOB,
    attributes_attempted_at TIMESTAMP,
    status VARCHAR(16) NOT NULL DEFAULT 'ACTIVE',
    version BIGINT NOT NULL DEFAULT 0,
    document_id BIGINT,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_catalog_spu_attr_status ON catalog_spu(attributes_status);
CREATE INDEX IF NOT EXISTS idx_catalog_spu_category ON catalog_spu(category_path);
CREATE INDEX IF NOT EXISTS idx_catalog_spu_brand ON catalog_spu(brand);
CREATE INDEX IF NOT EXISTS idx_catalog_spu_document_id ON catalog_spu(document_id);

CREATE TABLE IF NOT EXISTS catalog_sku (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    spu_id BIGINT NOT NULL,
    sku_code VARCHAR(64) NOT NULL,
    spec_json CLOB NOT NULL DEFAULT '{}',
    price DECIMAL(10, 2) NOT NULL,
    stock INTEGER NOT NULL DEFAULT 0,
    status VARCHAR(16) NOT NULL DEFAULT 'ACTIVE',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_catalog_sku_code UNIQUE (spu_id, sku_code)
);

CREATE INDEX IF NOT EXISTS idx_catalog_sku_spu_id ON catalog_sku(spu_id);

CREATE TABLE IF NOT EXISTS catalog_attribute_outbox (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    spu_id BIGINT NOT NULL,
    external_ref VARCHAR(64) NOT NULL,
    payload_json CLOB NOT NULL DEFAULT '{}',
    status VARCHAR(16) NOT NULL DEFAULT 'PENDING',
    attempt_count INTEGER NOT NULL DEFAULT 0,
    last_error CLOB,
    next_send_after TIMESTAMP,
    message_id VARCHAR(128),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_catalog_attr_outbox_status_next
    ON catalog_attribute_outbox(status, next_send_after);
CREATE INDEX IF NOT EXISTS idx_catalog_attr_outbox_spu_id
    ON catalog_attribute_outbox(spu_id);
