CREATE TABLE IF NOT EXISTS rag_documents (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_type VARCHAR(32) NOT NULL,
    source_uri VARCHAR(1024),
    external_ref VARCHAR(255),
    title VARCHAR(512),
    content CLOB NOT NULL,
    content_sha256 CHAR(64) NOT NULL,
    indexed_generation BIGINT,
    status VARCHAR(16) NOT NULL DEFAULT 'PENDING',
    chunk_count INTEGER NOT NULL DEFAULT 0,
    attempt_count INTEGER NOT NULL DEFAULT 0,
    metadata CLOB NOT NULL DEFAULT '{}',
    last_error CLOB,
    last_attempted_at TIMESTAMP,
    indexed_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS rag_index_jobs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    document_id BIGINT NOT NULL,
    content_sha256 CHAR(64) NOT NULL,
    status VARCHAR(16) NOT NULL DEFAULT 'QUEUED',
    stage VARCHAR(32) NOT NULL DEFAULT 'QUEUED',
    version BIGINT NOT NULL DEFAULT 0,
    last_event VARCHAR(64),
    attempt_count INTEGER NOT NULL DEFAULT 0,
    target_generation BIGINT,
    message_id VARCHAR(128),
    last_error CLOB,
    started_at TIMESTAMP,
    finished_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_rag_index_jobs_document_sha UNIQUE (document_id, content_sha256)
);

CREATE TABLE IF NOT EXISTS rag_index_job_transitions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    document_id BIGINT NOT NULL,
    job_id BIGINT,
    outbox_id BIGINT,
    content_sha256 CHAR(64) NOT NULL,
    from_state VARCHAR(32),
    to_state VARCHAR(32) NOT NULL,
    event VARCHAR(64) NOT NULL,
    trigger_type VARCHAR(32) NOT NULL,
    triggered_by VARCHAR(255),
    success BOOLEAN NOT NULL DEFAULT TRUE,
    failure_reason VARCHAR(64),
    error_message CLOB,
    message_id VARCHAR(128),
    metadata CLOB NOT NULL DEFAULT '{}',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS rag_index_outbox (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    document_id BIGINT NOT NULL,
    content_sha256 CHAR(64) NOT NULL,
    event_type VARCHAR(32) NOT NULL,
    status VARCHAR(16) NOT NULL DEFAULT 'NEW',
    attempt_count INTEGER NOT NULL DEFAULT 0,
    message_id VARCHAR(128),
    last_error CLOB,
    next_attempt_at TIMESTAMP,
    dispatched_at TIMESTAMP,
    consumed_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_rag_index_outbox_document_sha_event UNIQUE (document_id, content_sha256, event_type)
);

CREATE TABLE IF NOT EXISTS rag_index_message_failures (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    message_id VARCHAR(128) NOT NULL,
    topic VARCHAR(255) NOT NULL,
    delivery_attempt INTEGER NOT NULL,
    failure_type VARCHAR(32) NOT NULL,
    error_message CLOB,
    payload_base64 CLOB,
    payload_preview CLOB,
    properties_json CLOB NOT NULL DEFAULT '{}',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS rag_chunks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    document_id BIGINT NOT NULL,
    index_generation BIGINT NOT NULL DEFAULT 1,
    chunk_index INTEGER NOT NULL,
    chunk_text CLOB NOT NULL,
    chunk_hash CHAR(64) NOT NULL,
    char_count INTEGER NOT NULL DEFAULT 0,
    token_count INTEGER,
    vector_id VARCHAR(128),
    metadata CLOB NOT NULL DEFAULT '{}',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_rag_chunks_document_generation_chunk UNIQUE (document_id, index_generation, chunk_index)
);

CREATE TABLE IF NOT EXISTS rag_embedding_cache (
    chunk_hash CHAR(64) NOT NULL,
    embedding_model VARCHAR(255) NOT NULL,
    embedding_dimension INTEGER NOT NULL,
    embedding_json CLOB NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (chunk_hash, embedding_model, embedding_dimension)
);
