#!/usr/bin/env python3
from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any

import faiss
import numpy as np


def load_embedding_rows(path: Path) -> list[dict[str, Any]]:
    rows: list[dict[str, Any]] = []
    with path.open("r", encoding="utf-8") as file:
        for line in file:
            if not line.strip():
                continue
            row = json.loads(line)
            if not row.get("embedding"):
                continue
            rows.append(row)
    if not rows:
        raise ValueError(f"embedding file has no rows: {path}")
    return rows


def load_chunks_by_id(path: Path | None) -> dict[str, dict[str, Any]]:
    if path is None:
        return {}
    chunks: dict[str, dict[str, Any]] = {}
    with path.open("r", encoding="utf-8") as file:
        for line_no, line in enumerate(file, start=1):
            if not line.strip():
                continue
            row = json.loads(line)
            chunk_id = row.get("chunk_id")
            if not chunk_id:
                raise ValueError(f"chunk_id is missing at {path}:{line_no}")
            chunks[chunk_id] = row
    return chunks


def stable_faiss_id(index: int) -> int:
    return index + 1


def build_vectors(rows: list[dict[str, Any]]) -> np.ndarray:
    vectors = np.array([row["embedding"] for row in rows], dtype="float32")
    if vectors.ndim != 2:
        raise ValueError(f"expected 2D embedding matrix, got shape={vectors.shape}")
    faiss.normalize_L2(vectors)
    return vectors


def build_id_map(rows: list[dict[str, Any]], chunks_by_id: dict[str, dict[str, Any]]) -> list[dict[str, Any]]:
    id_map = []
    for index, row in enumerate(rows):
        chunk = chunks_by_id.get(row["chunk_id"]) or {}
        id_map.append(
            {
                "faiss_id": stable_faiss_id(index),
                "chunk_id": row["chunk_id"],
                "product_id": row["product_id"],
                "parent_chunk_id": row.get("parent_chunk_id"),
                "chunk_type": row["chunk_type"],
                "chunk_index": row["chunk_index"],
                "embedding_modality": row.get("embedding_modality"),
                "embedding_fingerprint": row.get("embedding_fingerprint"),
                "model": row["model"],
                "dimension": row["dimension"],
                "vector_id": row["vector_id"],
                "metadata": chunk.get("metadata") or row.get("metadata") or {},
                "source_ref": chunk.get("source_ref") or row.get("source_ref") or {},
            }
        )
    return id_map


def write_json(path: Path, payload: Any) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(payload, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")


def main() -> None:
    parser = argparse.ArgumentParser(description="Build local FAISS index for ecommerce embeddings.")
    parser.add_argument(
        "--embeddings",
        default="../../src/main/resources/db/ecommerce_offline/ecom-product-embeddings.jsonl",
        help="Embedding JSONL generated by embed_chunks_doubao.py.",
    )
    parser.add_argument(
        "--index-output",
        default="../../src/main/resources/db/ecommerce_offline/faiss/ecom-product.index",
        help="FAISS index output path.",
    )
    parser.add_argument(
        "--id-map-output",
        default="../../src/main/resources/db/ecommerce_offline/faiss/ecom-product-id-map.json",
        help="FAISS id mapping JSON output path.",
    )
    parser.add_argument(
        "--summary-output",
        default="../../src/main/resources/db/ecommerce_offline/faiss/ecom-product-faiss-summary.json",
        help="FAISS build summary output path.",
    )
    parser.add_argument(
        "--chunks",
        default="../../src/main/resources/db/ecommerce_offline/ecom-product-chunks.jsonl",
        help="Latest chunk JSONL path used to enrich FAISS id-map metadata.",
    )
    args = parser.parse_args()

    script_dir = Path(__file__).resolve().parent
    embeddings_path = (script_dir / args.embeddings).resolve()
    index_output = (script_dir / args.index_output).resolve()
    id_map_output = (script_dir / args.id_map_output).resolve()
    summary_output = (script_dir / args.summary_output).resolve()
    chunks_path = (script_dir / args.chunks).resolve() if args.chunks else None

    rows = load_embedding_rows(embeddings_path)
    chunks_by_id = load_chunks_by_id(chunks_path)
    vectors = build_vectors(rows)
    dimension = vectors.shape[1]

    base_index = faiss.IndexFlatIP(dimension)
    index = faiss.IndexIDMap2(base_index)
    ids = np.array([stable_faiss_id(index) for index in range(len(rows))], dtype="int64")
    index.add_with_ids(vectors, ids)

    index_output.parent.mkdir(parents=True, exist_ok=True)
    faiss.write_index(index, str(index_output))

    id_map = build_id_map(rows, chunks_by_id)
    write_json(id_map_output, id_map)

    by_modality: dict[str, int] = {}
    by_type: dict[str, int] = {}
    for row in rows:
        modality = row.get("embedding_modality") or "unknown"
        chunk_type = row.get("chunk_type") or "unknown"
        by_modality[modality] = by_modality.get(modality, 0) + 1
        by_type[chunk_type] = by_type.get(chunk_type, 0) + 1

    summary = {
        "embeddings": str(embeddings_path),
        "index_output": str(index_output),
        "id_map_output": str(id_map_output),
        "chunks": str(chunks_path) if chunks_path else None,
        "vector_count": len(rows),
        "dimension": dimension,
        "metric": "inner_product_on_l2_normalized_vectors",
        "by_modality": dict(sorted(by_modality.items())),
        "by_chunk_type": dict(sorted(by_type.items())),
    }
    write_json(summary_output, summary)
    print(json.dumps(summary, ensure_ascii=False, indent=2))


if __name__ == "__main__":
    main()
