#!/usr/bin/env python3
from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any


def sql_string(value: Any) -> str:
    if value is None:
        return "NULL"
    return "'" + str(value).replace("'", "''") + "'"


def load_embeddings(path: Path) -> list[dict[str, Any]]:
    rows: list[dict[str, Any]] = []
    seen: set[tuple[str, str, str]] = set()
    with path.open("r", encoding="utf-8") as file:
        for line_no, line in enumerate(file, start=1):
            if not line.strip():
                continue
            row = json.loads(line)
            key = (row["chunk_id"], row["embedding_fingerprint"], row["model"])
            if key in seen:
                raise ValueError(f"duplicate embedding row at line {line_no}: {key}")
            seen.add(key)
            rows.append(row)
    if not rows:
        raise ValueError(f"embedding file has no rows: {path}")
    return rows


def write_values_insert(file, rows: list[dict[str, Any]]) -> None:
    file.write(
        """
CREATE TEMP TABLE seed_embedding_status (
    chunk_id varchar(128) PRIMARY KEY,
    vector_id varchar(256) NOT NULL,
    embedding_model varchar(255) NOT NULL,
    embedding_dimension integer NOT NULL,
    embedding_modality varchar(16) NOT NULL,
    embedding_fingerprint text NOT NULL
) ON COMMIT DROP;

INSERT INTO seed_embedding_status (
    chunk_id,
    vector_id,
    embedding_model,
    embedding_dimension,
    embedding_modality,
    embedding_fingerprint
)
VALUES
""".lstrip()
    )
    for index, row in enumerate(rows):
        suffix = "," if index < len(rows) - 1 else ""
        file.write(
            "    ("
            + ", ".join(
                [
                    sql_string(row["chunk_id"]),
                    sql_string(row["vector_id"]),
                    sql_string(row["model"]),
                    str(int(row["dimension"])),
                    sql_string(row["embedding_modality"]),
                    sql_string(row["embedding_fingerprint"]),
                ]
            )
            + ")"
            + suffix
            + "\n"
        )
    file.write(";\n\n")


def generate_sql(rows: list[dict[str, Any]], output: Path) -> None:
    output.parent.mkdir(parents=True, exist_ok=True)
    with output.open("w", encoding="utf-8", newline="\n") as file:
        file.write("-- Generated by scripts/ecommerce_offline/sync_embedding_status_sql.py\n")
        file.write("-- Updates ecommerce_offline.ecom_product_chunk after FAISS/embedding build.\n\n")
        file.write("BEGIN;\n\n")
        write_values_insert(file, rows)
        file.write(
            """
UPDATE ecommerce_offline.ecom_product_chunk c
   SET vector_id = s.vector_id,
       embedding_status = 'INDEXED',
       embedding_model = s.embedding_model,
       embedding_dimension = s.embedding_dimension,
       embedding_attempt_count = GREATEST(c.embedding_attempt_count, 1),
       embedding_last_error = NULL,
       embedding_attempted_at = now(),
       embedded_at = now(),
       updated_at = now()
  FROM seed_embedding_status s
 WHERE c.chunk_id = s.chunk_id
   AND c.embedding_required = true
   AND c.embedding_modality = s.embedding_modality;

UPDATE ecommerce_offline.ecom_product_chunk
   SET embedding_status = 'SKIPPED',
       embedding_last_error = NULL,
       updated_at = now()
 WHERE embedding_required = false
   AND embedding_status <> 'SKIPPED';

UPDATE ecommerce_offline.ecom_product_chunk c
   SET embedding_status = 'FAILED',
       embedding_attempt_count = c.embedding_attempt_count + 1,
       embedding_last_error = 'embedding result missing from seed_embedding_status',
       embedding_attempted_at = now(),
       updated_at = now()
 WHERE c.embedding_required = true
   AND NOT EXISTS (
       SELECT 1
         FROM seed_embedding_status s
        WHERE s.chunk_id = c.chunk_id
   );

COMMIT;

SELECT embedding_status, embedding_modality, count(*) AS count
FROM ecommerce_offline.ecom_product_chunk
GROUP BY embedding_status, embedding_modality
ORDER BY embedding_status, embedding_modality;
""".lstrip()
        )


def main() -> None:
    parser = argparse.ArgumentParser(description="Generate SQL to sync embedding status back to ecom_product_chunk.")
    parser.add_argument(
        "--embeddings",
        default="../../src/main/resources/db/ecommerce_offline/ecom-product-embeddings.jsonl",
    )
    parser.add_argument(
        "--output",
        default="../../src/main/resources/db/ecommerce_offline/update-embedding-status.sql",
    )
    args = parser.parse_args()

    script_dir = Path(__file__).resolve().parent
    embeddings = (script_dir / args.embeddings).resolve()
    output = (script_dir / args.output).resolve()
    rows = load_embeddings(embeddings)
    generate_sql(rows, output)
    print(json.dumps({
        "embeddings": str(embeddings),
        "output": str(output),
        "row_count": len(rows),
    }, ensure_ascii=False, indent=2))


if __name__ == "__main__":
    main()
